fix: Remove non-existent discount_percentage field from query
BUG: Query was trying to select 'discount_percentage' which doesn't exist in discount_sales table
Error: column discount_sales.discount_percentage does not exist (code 42703)

FIXED:
- Removed discount_percentage from SELECT
- Keep discount_type and discount_reason which DO exist

Now discount_sales load correctly and discount reasons display!